language: cpp
sudo: required
compiler:
 - gcc
 - clang
install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-i386.tar.gz
      && tar -xzfv cmake-3.3.1-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.3.1-Linux-i386/* /usr
      && sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
      && sudo add-apt-repository -y "deb http://repos.codelite.org/wx3.0.2/ubuntu/ trusty universe"
      && sudo apt-get update
      && sudo apt-get install cmake libwxbase3.0-dev libwxgtk3.0-dev wx3.0-headers wx-common 
      ;
   else
      brew update
   && brew unlink cmake
   && brew install cmake
   && brew install wxmac
      ;
   fi
   
script:
 - cmake . -DWX_UI=ON
 - make

matrix:
 allow_failures:
  - os: osx
