sudo: required
env:
 - DOCKER_IMAGE="ubuntu:xenial" PKG="DEB"
 - DOCKER_IMAGE="ubuntu:bionic" PKG="DEB"
 - DOCKER_IMAGE="debian:buster" PKG="DEB"
 - DOCKER_IMAGE="fedora:31" PKG="DNF"
 - DOCKER_IMAGE="fedora:latest" PKG="DNF"
 - DOCKER_IMAGE="opensuse:tumbleweed" PKG="ZYPPER"
services:
 - docker
install:
 - docker pull $DOCKER_IMAGE
script:
 - if [ "${PKG}" = "DEB" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && apt-get update && apt-get install -y cmake g++ libwxgtk3.0-dev libwxbase3.0-dev wx3.0-headers wx-common libxml2-utils python && ./build_wx.sh" 
      ;
      fi
 - if [ "${PKG}" = "DNF" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && dnf -y install cmake gcc-c++ wxGTK3-devel wxGTK3-gl gcc make python libxml2-devel && ./build_wx.sh"
      ;
   fi
 - if [ "${PKG}" = "ZYPPER" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && zypper --non-interactive refresh && zypper --non-interactive install cmake gcc-c++ wxWidgets-2_9 && ./build_wx.sh"
       ;
   fi

matrix:
 allow_failures:
  - env: DOCKER_IMAGE="ubuntu:xenial" PKG="DEB"
  - env: DOCKER_IMAGE="debian:buster" PKG="DEB"
  - env: DOCKER_IMAGE="fedora:31" PKG="DNF"
  - env: DOCKER_IMAGE="fedora:latest" PKG="DNF"
  - env: DOCKER_IMAGE="opensuse:tumbleweed" PKG="ZYPPER"
