language: cpp
sudo: required
compiler:
 - gcc
 - clang
install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-i386.tar.gz -O CMAKE.tar.gz
      && tar -xzf CMAKE.tar.gz
      && sudo apt-get update
      && sudo apt-get install libwxbase2.8-dev libwxgtk2.8-dev wx2.8-headers wx-common 
      ;
   else
      brew update
   && brew unlink cmake
   && brew install cmake
   && brew install wxmac
      ;
   fi
   
script:
 - cmake-3.3.1-Linux-i386/cmake . -DWX_UI=ON
 - make

matrix:
 allow_failures:
  - os: osx
