sudo: required
env:
 - DOCKER_IMAGE="ubuntu:trusty"
 - DOCKER_IMAGE="ubuntu:vivid"
 - DOCKER_IMAGE="ubuntu:wily"
 - DOCKER_IMAGE="debian:jessie"
 - DOCKER_IMAGE="debian:sid"
services:
 - docker
install:
 - docker pull $DOCKER_IMAGE
script:
 - docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && apt-get update && apt-get install -y cmake g++ libwxgtk3.0-dev libwxbase3.0-dev wx3.0-headers wx-common && cmake . -DWX_UI=ON && make" 

matrix:
 allow_failures:
  - env: DOCKER_IMAGE="ubuntu:trusty"
