sudo: required
env:
 - DOCKER_IMAGE="ubuntu:trusty" PKG="DEB"
 - DOCKER_IMAGE="ubuntu:vivid" PKG="DEB"
 - DOCKER_IMAGE="ubuntu:wily" PKG="DEB"
 - DOCKER_IMAGE="debian:jessie" PKG="DEB"
 - DOCKER_IMAGE="debian:sid" PKG="DEB"
 - DOCKER_IMAGE="fedora:22" PKG="DNF"
 - DOCKER_IMAGE="opensuse:tumbleweed" PKG="ZYPPER"
services:
 - docker
install:
 - docker pull $DOCKER_IMAGE
script:
 - if [ "${PKG}" = "DEB" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && apt-get update && apt-get install software-properties-common && add-apt-repository -y "deb http://ppa.launchpad.net/adrian-arroyocalle/general/ubuntu trusty main" && apt-get update && apt-get install -y cmake g++ libwxgtk3.0-dev libwxbase3.0-dev wx3.0-headers wx-common && cmake . -DWX_UI=ON && make" 
      ;
      fi
 - if [ "${PKG}" = "DNF" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && dnf -y install cmake gcc-c++ wxGTK-devel && cmake . -DWX_UI=ON && make"
      ;
   fi
 - if [ "${PKG}" = "ZYPPER" ]; then
       docker run -v $PWD:/cmake -t $DOCKER_IMAGE /bin/bash -c "cd /cmake && zypper refresh && zypper --non-interactive install cmake gcc-c++ wxWidgets-devel && cmake . -DWX_UI=ON && make"
       ;
   fi

matrix:
 allow_failures:
  - env: DOCKER_IMAGE="ubuntu:trusty" PKG="DEB"
  - env: DOCKER_IMAGE="ubuntu:vivid" PKG="DEB"
  - env: DOCKER_IMAGE="debian:jessie" PKG="DEB"
  - env: DOCKER_IMAGE="debian:sid" PKG="DEB"
  - env: DOCKER_IMAGE="fedora:22" PKG="DNF"
  - env: DOCKER_IMAGE="opensuse:tumbleweed" PKG="ZYPPER"
